# $FreeBSD$

PORTNAME=	signify-port
PORTVERSION=	6.3
CATEGORIES=	rescrv
MASTER_SITES=	http://rescrv.net/src/

MAINTAINER=	robert@rescrv.net
COMMENT=	Port of signify to work on Linux and FreeBSD.

LICENSE=	BSD

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
