#!/usr/bin/env python3

import os
import os.path

class IterRegistry(type):

    def __iter__(cls):
        return iter(cls._registry)

class Package(metaclass=IterRegistry):
    _registry = []

    def __init__(self, name, version):
        self._registry.append(self)
        self.name = name
        self.version = version
        self.depends = []
        self.uses = set()

    def depends_upon(self, port, pkg=None):
        if pkg is None:
            pkg = port.split('/')[-1]
            if pkg.startswith('py-'):
                pkg = '${PYTHON_PKGNAMEPREFIX}' + pkg[3:]
                self.uses.add('python')
        self.depends.append((pkg, port))

    def write_port(self):
        if not os.path.exists('rescrv/%s' % self.name):
            os.makedirs('rescrv/%s' % self.name)
        f = open('rescrv/%s/Makefile' % self.name, 'w')
        deps = '\n'.join(['RUN_DEPENDS+=	%s>0:${PORTSDIR}/%s' %
                                (x[0].replace('@', '-'), x[1])
                          for x in self.depends])
        uses = ''
        if self.uses:
            uses += 'USES= ' + ' '.join(sorted(self.uses)) + '\n'
        f.write('''PORTNAME=      rescrv-{0}
PORTVERSION=   {1}
CATEGORIES=    rescrv
MASTER_SITES=  # none
DISTFILES=     # none
EXTRACT_ONLY=  # none

MAINTAINER=    robert@rescrv.net
COMMENT=       {0} meta package

NO_MTREE=      yes
NO_BUILD=      yes
NO_WRKSUBDIR=  yes

USES=          metaport

{2}
{3}
do-install: build
		@${{DO_NADA}}

.include <bsd.port.mk>
'''.format(self.name, self.version, deps, uses))
        f.flush()
        f.close()
        f = open('rescrv/%s/pkg-descr' % self.name, 'w')
        f.write('%s meta package\n' % self.name)
        f.flush()
        f.close()

p = Package('minimal', 20230408)
p.depends_upon('archivers/redupe')
p.depends_upon('dns/bind-tools')
p.depends_upon('editors/vim@console', 'vim')
p.depends_upon('ftp/wget')
p.depends_upon('lang/python2')
p.depends_upon('lang/python3')
p.depends_upon('net/rsync')
p.depends_upon('rescrv/signify', 'signify-port')
p.depends_upon('security/encryptify')
p.depends_upon('security/keychain')
p.depends_upon('shells/bash')
p.depends_upon('shells/zsh')
p.depends_upon('sysutils/stow')
p.depends_upon('sysutils/tmux')
p.depends_upon('www/w3m')

p = Package('builder', 20200423)
p.depends_upon('rescrv/minimal', 'rescrv-minimal')
p.depends_upon('devel/git@lite')
p.depends_upon('ports-mgmt/portlint')
p.depends_upon('ports-mgmt/portshaker')
p.depends_upon('ports-mgmt/poudriere')

p = Package('devel', 20210917)
p.depends_upon('rescrv/minimal', 'rescrv-minimal')
p.depends_upon('devel/git@lite')
p.depends_upon('lang/rust')

p = Package('writing', 20230407)
p.depends_upon('rescrv/minimal', 'rescrv-minimal')
p.depends_upon('math/gnuplot-lite')
p.depends_upon('textproc/hs-pandoc')
p.depends_upon('textproc/py-markdown')
p.depends_upon('textproc/py-pygments')
p.depends_upon('www/py-pelican')
p.depends_upon('www/tidy', 'tidy4')

p = Package('photography', 20190410)

p = Package('multimedia', 20230515)
p.depends_upon('multimedia/ffmpeg')
p.depends_upon('multimedia/mplayer')
p.depends_upon('multimedia/x264')

meta_deps = []
max_version = 0

for p in Package:
    p.write_port()
    max_version = max(max_version, p.version)
    meta_deps.append(p.name)

meta = Package('all', max_version)
for d in meta_deps:
    meta.depends_upon('rescrv/%s' % d, 'rescrv-%s' % d)
meta.write_port()
