PORTNAME=      rescrv-executive
PORTVERSION=   20190928
CATEGORIES=    rescrv
MASTER_SITES=  # none
DISTFILES=     # none
EXTRACT_ONLY=  # none

MAINTAINER=    robert@rescrv.net
COMMENT=       executive meta package

NO_BUILD=      yes
NO_WRKSUBDIR=  yes

RUN_DEPENDS+=	taskwarrior>0:${PORTSDIR}/deskutils/taskwarrior

do-install: build
		@${DO_NADA}

.include <bsd.port.mk>
