PORTNAME=      rescrv-photography
PORTVERSION=   20190331
CATEGORIES=    rescrv
MASTER_SITES=  # none
DISTFILES=     # none
EXTRACT_ONLY=  # none

MAINTAINER=    robert@rescrv.net
COMMENT=       photography meta package

NO_BUILD=      yes
NO_WRKSUBDIR=  yes

RUN_DEPENDS+=	hs-git-annex>0:${PORTSDIR}/devel/hs-git-annex

do-install: build
		@${DO_NADA}

.include <bsd.port.mk>
